name: CI

on:
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    name: Build, Test & Lint
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: '.nvmrc'

      - name: Enable corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build, Test, & Lint all packages
        run: pnpm run ci
