name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create .npmrc
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc

      - name: Setup pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: pnpm i

      # This will run all build, test, and lint scripts in parallel for all packages
      - name: Build, Test, & Lint all packages
        run: pnpm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          title: 'Changesets: Versioning & Publishing'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Get current branch
        id: get_branch
        run: echo "CURRENT_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV

      - name: Update lock file
        if: env.CURRENT_BRANCH == 'changeset-release/main'
        run: pnpm install --lockfile-only

      # Reset all changes and do a verified commit via api
      # This is to ensure all commits are signed and the pr can be merged
      - name: Reset all changes
        if: env.CURRENT_BRANCH == 'changeset-release/main'
        run: git reset --soft $(git merge-base main changeset-release/main)

      - name: Get all changed files
        if: env.CURRENT_BRANCH == 'changeset-release/main'
        run: |
          {
            echo 'CHANGED_FILES<<EOF'
            git diff --name-only --cached
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Do a verified commit via api
        if: env.CURRENT_BRANCH == 'changeset-release/main'
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.CHANGED_FILES }}
          commit-message: 'chore: changeset release'
          ref: refs/heads/changeset-release/main
